---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options
# See https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md for documentation

title: "Bienvenue sur ****.lol"
subtitle: "Liste des services"
documentTitle: "****.lol"
logo: "assets/logo.png"

header: true
footer: '<p>Créé par <a href="https://alix.anneraud.fr">Alix</a>, <a href="https://mastodon.insa.lol/@dimitri_timoz">Dimitri</a> et <a href="https://mastodon.insa.lol/@simon_girard">Simon</a></p>' # set false if you want to hide it.

columns: "auto" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: true

# Set the default layout and color scheme
defaults:
  layout: columns
  colorTheme: dark

# Optional theming
theme: default # 'default' or one of the themes available in 'src/assets/themes'.

stylesheet:
  - "assets/custom.css"

colors:
  light:
    highlight-primary: "#DC6ACF"
    highlight-secondary: "#f4a6eb"
    highlight-hover: "#f475e5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#424242"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#f475e5"
    link-hover: "#DC6ACF"
  dark:
    highlight-primary: "#DC6ACF"
    highlight-secondary: "#c15db6"
    highlight-hover: "#DC6ACF"
    background: "#241b22"
    card-background: "#393037"
    text: "#fafafa"
    text-header: "#fff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: none
    link: "#c15db6"
    link-hover: "#DC6ACF"

message:
  style: "is-info"
  title: "Rejoignez-nous !"
  icon: "far fa-lightbulb"
  content: |
    Vous avez une idée de service à proposer aux étudiants ? Nous pouvons vous aider et soutenir ! Voici les outils que nous pouvons mettre à votre disposition :
    <ul>
        <li>- Sous-domaine</li>
        <li>- Authentification</li>
        <li>- Envoi d'emails</li>
        <li>- Hébergement</li>
        <li>- Analytics (Plausible)</li>
        <li>- Mise en avant</li>
    </ul>
    <br/>
    Nous ne sommes pas affiliés à l'organisation dont le nom figure dans le nom de domaine. Nous sommes un groupe d'étudiants qui essayons de simplifier la vie des étudiants. Si vous avez des questions, n'hésitez pas à nous contacter !

links:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/INSAgenda"
  - name: "Discord"
    icon: "fa-brands fa-discord"
    url: "https://discord.gg/TpdbUyfcbJ"
  - name: "Email"
    icon: "fa fa-envelope"
    url: "mailto:sgirard@insa-rouen.fr,dtimoz@insa-rouen.fr,aanneraud@insa-rouen.fr"
  - name: "Status"
    icon: "fas fa-heartbeat"
    url: "https://status.insa.lol/"

services:
  - name: "Outils"
    icon: "fas fa-tools"
    items:
      - name: "genda"
        logo: "assets/insagenda.svg"
        subtitle: "Consultez votre emploi du temps et celui de vos amis"
        tag: "agenda"
        keywords: "emploi du temps et agenda"
        url: "https://insagenda.insa.lol/"

      - name: "Outline"
        logo: "assets/outline.svg"
        subtitle: "Partagez et éditez des documents à plusieurs"
        tag: "outline"
        keywords: "documents docs outline markdown latex"
        url: "https://docs.insa.lol/"

      # Abandonné
      # 
      # - name: "Wifi WPA"
      #   logo: "assets/wifi.png"
      #   subtitle: "Obtenez le mot de passe du wifi"
      #   tag: "wifi"
      #   keywords: "wifi et mot de passe"
      #   url: "https://mastodon.insa.lol/@wifi"

      - name: "login-rememberer"
        logo: "assets/login.svg"
        subtitle: "Restez connectés pour toujours au CAS"
        tag: "cas"
        keywords: "login et mot de passe"
        url: "https://github.com/Mubelotix/insa-login-rememberer"

      # - name: "Search (en projet)"
      #   logo: "assets/search.svg"
      #   subtitle: "Recherchez sur tout le réseau privé"
      #   tag: "search"
      #   keywords: "moteur de recherche"

      - name: "Scan (abandonné)"
        logo: "assets/scan.svg"
        subtitle: "Listez les machines"
        tag: "scan"
        keywords: "liste les machines allumées pour vous y connecter en SSH"
        url: "https://scan.insa.lol/"

  - name: "Social"
    icon: "fas fa-users"
    items:
      - name: "Matrix"
        logo: "assets/matrix.svg"
        subtitle: "Discutez avec les autres étudiants"
        tag: "matrix"
        keywords: "chat et messagerie instantanée"
        url: "https://element.insa.lol/"

      # Pas encore disponible
      # 
      # - name: "Instagram amélioré"
      #   logo: "assets/instagram.svg"
      #   subtitle: "Instagram sans publicités"
      #   tag: "instagram"
      #   keywords: "réseau social et photos"
      #   url: "https://fdroid.insa.lol/"

      # TODO: use https://github.com/crimera/piko
      # 
      # - name: Twitter amélioré
      #   logo: "assets/twitter.svg"
      #   subtitle: "Twitter sans publicités"
      #   tag: "twitter"
      #   keywords: "réseau social et microblogging"
      #   url: "https://fdroid.insa.lol/"

      - name: "Stotra"
        logo: "assets/stotra.svg"
        subtitle: "Classez-vous face aux autres étudiants dans ce simulateur d'investissement basé sur les cours réels de la bourse"
        tag: "bourse"
        keywords: "bourse et investissement"
        url: "https://stotra.insa.lol/leaderboard"

      - name: "Pixel War (terminé)"
        logo: "assets/pixelwar.ico"
        subtitle: "Participez à pixel war 2024 pour les 3A !"
        tag: "pixelwar"
        keywords: "jeu et pixel art"
        url: "https://pixelwar.insa.lol/"

      - name: "Mastodon (abandonné)"
        logo: "assets/mastodon.svg"
        subtitle: "Suivez l'actualité de l'école"
        tag: "mastodon"
        keywords: "réseau social et microblogging"
        url: "https://mastodon.insa.lol/public/local"
  
  - name: "Divertissement"
    icon: "fas fa-gamepad"
    items:
      # Abandonné
      # 
      # - name: "Movies"
      #   logo: "assets/movies.svg"
      #   subtitle: "Regardez des films et séries gratuitement"
      #   tag: "movies"
      #   keywords: "films et séries gratuits"
      #   url: "https://www.vidbinge.com/"

      # TODO: Le remettre
      # 
      # - name: "Free-Picolo"
      #   logo: "assets/picolo.webp"
      #   subtitle: "Jouez à la version premium de Picolo gratuitement"
      #   tag: "picolo"
      #   keywords: "jeu de soirée et à boire"
      #   url: "https://picolo.insa.lol/"

      # Censuré
      # 
      # - name: "Youtube amélioré"
      #   logo: "assets/youtube.svg"
      #   subtitle: "Youtube sans publicités, lecture en arrière plan et passage automatique des sponsors"
      #   tag: "youtube"
      #   keywords: "vidéos et streaming"
      #   url: "https://fdroid.insa.lol/"

      # Censuré
      # 
      # - name: "Youtube Music amélioré"
      #   logo: "assets/youtube-music.svg"
      #   subtitle: "Youtube Music sans publicités et lecture en arrière plan"
      #   tag: "youtube-music"
      #   keywords: "musique et streaming"
      #   url: "https://fdroid.insa.lol/"

      - name: "Stats"
        logo: "assets/stats.jpg"
        subtitle: "Consultez des statistiques variées sur l'école"
        tag: "stats"
        keywords: "statistiques et données"
        url: "https://instagram.com/insa_stats"
